/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedTaxesIndexRouteImport } from './routes/_authenticated/taxes/index'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers/index'
import { Route as AuthenticatedSeasonsIndexRouteImport } from './routes/_authenticated/seasons/index'
import { Route as AuthenticatedRoomTypesIndexRouteImport } from './routes/_authenticated/room-types/index'
import { Route as AuthenticatedRfqsIndexRouteImport } from './routes/_authenticated/rfqs/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedReceiptsIndexRouteImport } from './routes/_authenticated/receipts/index'
import { Route as AuthenticatedRatesIndexRouteImport } from './routes/_authenticated/rates/index'
import { Route as AuthenticatedQuotationsIndexRouteImport } from './routes/_authenticated/quotations/index'
import { Route as AuthenticatedPayablesIndexRouteImport } from './routes/_authenticated/payables/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedHotelsIndexRouteImport } from './routes/_authenticated/hotels/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts/index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings/index'
import { Route as AuthenticatedTaxesIdRouteImport } from './routes/_authenticated/taxes/$id'
import { Route as AuthenticatedSuppliersNewRouteImport } from './routes/_authenticated/suppliers/new'
import { Route as AuthenticatedSuppliersIdRouteImport } from './routes/_authenticated/suppliers/$id'
import { Route as AuthenticatedSeasonsIdRouteImport } from './routes/_authenticated/seasons/$id'
import { Route as AuthenticatedRoomTypesIdRouteImport } from './routes/_authenticated/room-types/$id'
import { Route as AuthenticatedRfqsNewRouteImport } from './routes/_authenticated/rfqs/new'
import { Route as AuthenticatedRfqsIdRouteImport } from './routes/_authenticated/rfqs/$id'
import { Route as AuthenticatedReportsTemplatesRouteImport } from './routes/_authenticated/reports/templates'
import { Route as AuthenticatedReportsTaxRouteImport } from './routes/_authenticated/reports/tax'
import { Route as AuthenticatedReportsOperationalRouteImport } from './routes/_authenticated/reports/operational'
import { Route as AuthenticatedReportsFinancialRouteImport } from './routes/_authenticated/reports/financial'
import { Route as AuthenticatedRatesNewRouteImport } from './routes/_authenticated/rates/new'
import { Route as AuthenticatedRatesCompareRouteImport } from './routes/_authenticated/rates/compare'
import { Route as AuthenticatedRatesIdRouteImport } from './routes/_authenticated/rates/$id'
import { Route as AuthenticatedQuotationsNewRouteImport } from './routes/_authenticated/quotations/new'
import { Route as AuthenticatedQuotationsIdRouteImport } from './routes/_authenticated/quotations/$id'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices/$id'
import { Route as AuthenticatedHotelsNewRouteImport } from './routes/_authenticated/hotels/new'
import { Route as AuthenticatedHotelsIdRouteImport } from './routes/_authenticated/hotels/$id'
import { Route as AuthenticatedCustomersNewRouteImport } from './routes/_authenticated/customers/new'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers/$id'
import { Route as AuthenticatedContractsNewRouteImport } from './routes/_authenticated/contracts/new'
import { Route as AuthenticatedContractsIdRouteImport } from './routes/_authenticated/contracts/$id'
import { Route as AuthenticatedBookingsNewRouteImport } from './routes/_authenticated/bookings/new'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaxesIndexRoute = AuthenticatedTaxesIndexRouteImport.update({
  id: '/taxes/',
  path: '/taxes/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeasonsIndexRoute =
  AuthenticatedSeasonsIndexRouteImport.update({
    id: '/seasons/',
    path: '/seasons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomTypesIndexRoute =
  AuthenticatedRoomTypesIndexRouteImport.update({
    id: '/room-types/',
    path: '/room-types/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfqsIndexRoute = AuthenticatedRfqsIndexRouteImport.update({
  id: '/rfqs/',
  path: '/rfqs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiptsIndexRoute =
  AuthenticatedReceiptsIndexRouteImport.update({
    id: '/receipts/',
    path: '/receipts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRatesIndexRoute = AuthenticatedRatesIndexRouteImport.update({
  id: '/rates/',
  path: '/rates/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsIndexRoute =
  AuthenticatedQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayablesIndexRoute =
  AuthenticatedPayablesIndexRouteImport.update({
    id: '/payables/',
    path: '/payables/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotelsIndexRoute =
  AuthenticatedHotelsIndexRouteImport.update({
    id: '/hotels/',
    path: '/hotels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTaxesIdRoute = AuthenticatedTaxesIdRouteImport.update({
  id: '/taxes/$id',
  path: '/taxes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersNewRoute =
  AuthenticatedSuppliersNewRouteImport.update({
    id: '/suppliers/new',
    path: '/suppliers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersIdRoute =
  AuthenticatedSuppliersIdRouteImport.update({
    id: '/suppliers/$id',
    path: '/suppliers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeasonsIdRoute = AuthenticatedSeasonsIdRouteImport.update({
  id: '/seasons/$id',
  path: '/seasons/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomTypesIdRoute =
  AuthenticatedRoomTypesIdRouteImport.update({
    id: '/room-types/$id',
    path: '/room-types/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfqsNewRoute = AuthenticatedRfqsNewRouteImport.update({
  id: '/rfqs/new',
  path: '/rfqs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRfqsIdRoute = AuthenticatedRfqsIdRouteImport.update({
  id: '/rfqs/$id',
  path: '/rfqs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsTemplatesRoute =
  AuthenticatedReportsTemplatesRouteImport.update({
    id: '/reports/templates',
    path: '/reports/templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsTaxRoute = AuthenticatedReportsTaxRouteImport.update({
  id: '/reports/tax',
  path: '/reports/tax',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsOperationalRoute =
  AuthenticatedReportsOperationalRouteImport.update({
    id: '/reports/operational',
    path: '/reports/operational',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsFinancialRoute =
  AuthenticatedReportsFinancialRouteImport.update({
    id: '/reports/financial',
    path: '/reports/financial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRatesNewRoute = AuthenticatedRatesNewRouteImport.update({
  id: '/rates/new',
  path: '/rates/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRatesCompareRoute =
  AuthenticatedRatesCompareRouteImport.update({
    id: '/rates/compare',
    path: '/rates/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRatesIdRoute = AuthenticatedRatesIdRouteImport.update({
  id: '/rates/$id',
  path: '/rates/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsNewRoute =
  AuthenticatedQuotationsNewRouteImport.update({
    id: '/quotations/new',
    path: '/quotations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsIdRoute =
  AuthenticatedQuotationsIdRouteImport.update({
    id: '/quotations/$id',
    path: '/quotations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHotelsNewRoute = AuthenticatedHotelsNewRouteImport.update({
  id: '/hotels/new',
  path: '/hotels/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHotelsIdRoute = AuthenticatedHotelsIdRouteImport.update({
  id: '/hotels/$id',
  path: '/hotels/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersNewRoute =
  AuthenticatedCustomersNewRouteImport.update({
    id: '/customers/new',
    path: '/customers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsNewRoute =
  AuthenticatedContractsNewRouteImport.update({
    id: '/contracts/new',
    path: '/contracts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIdRoute =
  AuthenticatedContractsIdRouteImport.update({
    id: '/contracts/$id',
    path: '/contracts/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsNewRoute =
  AuthenticatedBookingsNewRouteImport.update({
    id: '/bookings/new',
    path: '/bookings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/contracts/new': typeof AuthenticatedContractsNewRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/hotels/$id': typeof AuthenticatedHotelsIdRoute
  '/hotels/new': typeof AuthenticatedHotelsNewRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/rates/$id': typeof AuthenticatedRatesIdRoute
  '/rates/compare': typeof AuthenticatedRatesCompareRoute
  '/rates/new': typeof AuthenticatedRatesNewRoute
  '/reports/financial': typeof AuthenticatedReportsFinancialRoute
  '/reports/operational': typeof AuthenticatedReportsOperationalRoute
  '/reports/tax': typeof AuthenticatedReportsTaxRoute
  '/reports/templates': typeof AuthenticatedReportsTemplatesRoute
  '/rfqs/$id': typeof AuthenticatedRfqsIdRoute
  '/rfqs/new': typeof AuthenticatedRfqsNewRoute
  '/room-types/$id': typeof AuthenticatedRoomTypesIdRoute
  '/seasons/$id': typeof AuthenticatedSeasonsIdRoute
  '/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/suppliers/new': typeof AuthenticatedSuppliersNewRoute
  '/taxes/$id': typeof AuthenticatedTaxesIdRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/hotels/': typeof AuthenticatedHotelsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/payables/': typeof AuthenticatedPayablesIndexRoute
  '/quotations/': typeof AuthenticatedQuotationsIndexRoute
  '/rates/': typeof AuthenticatedRatesIndexRoute
  '/receipts/': typeof AuthenticatedReceiptsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/rfqs/': typeof AuthenticatedRfqsIndexRoute
  '/room-types/': typeof AuthenticatedRoomTypesIndexRoute
  '/seasons/': typeof AuthenticatedSeasonsIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/taxes/': typeof AuthenticatedTaxesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/contracts/new': typeof AuthenticatedContractsNewRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/hotels/$id': typeof AuthenticatedHotelsIdRoute
  '/hotels/new': typeof AuthenticatedHotelsNewRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/rates/$id': typeof AuthenticatedRatesIdRoute
  '/rates/compare': typeof AuthenticatedRatesCompareRoute
  '/rates/new': typeof AuthenticatedRatesNewRoute
  '/reports/financial': typeof AuthenticatedReportsFinancialRoute
  '/reports/operational': typeof AuthenticatedReportsOperationalRoute
  '/reports/tax': typeof AuthenticatedReportsTaxRoute
  '/reports/templates': typeof AuthenticatedReportsTemplatesRoute
  '/rfqs/$id': typeof AuthenticatedRfqsIdRoute
  '/rfqs/new': typeof AuthenticatedRfqsNewRoute
  '/room-types/$id': typeof AuthenticatedRoomTypesIdRoute
  '/seasons/$id': typeof AuthenticatedSeasonsIdRoute
  '/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/suppliers/new': typeof AuthenticatedSuppliersNewRoute
  '/taxes/$id': typeof AuthenticatedTaxesIdRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/hotels': typeof AuthenticatedHotelsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/payables': typeof AuthenticatedPayablesIndexRoute
  '/quotations': typeof AuthenticatedQuotationsIndexRoute
  '/rates': typeof AuthenticatedRatesIndexRoute
  '/receipts': typeof AuthenticatedReceiptsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/rfqs': typeof AuthenticatedRfqsIndexRoute
  '/room-types': typeof AuthenticatedRoomTypesIndexRoute
  '/seasons': typeof AuthenticatedSeasonsIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/taxes': typeof AuthenticatedTaxesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/_authenticated/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/_authenticated/contracts/new': typeof AuthenticatedContractsNewRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/customers/new': typeof AuthenticatedCustomersNewRoute
  '/_authenticated/hotels/$id': typeof AuthenticatedHotelsIdRoute
  '/_authenticated/hotels/new': typeof AuthenticatedHotelsNewRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/_authenticated/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/_authenticated/rates/$id': typeof AuthenticatedRatesIdRoute
  '/_authenticated/rates/compare': typeof AuthenticatedRatesCompareRoute
  '/_authenticated/rates/new': typeof AuthenticatedRatesNewRoute
  '/_authenticated/reports/financial': typeof AuthenticatedReportsFinancialRoute
  '/_authenticated/reports/operational': typeof AuthenticatedReportsOperationalRoute
  '/_authenticated/reports/tax': typeof AuthenticatedReportsTaxRoute
  '/_authenticated/reports/templates': typeof AuthenticatedReportsTemplatesRoute
  '/_authenticated/rfqs/$id': typeof AuthenticatedRfqsIdRoute
  '/_authenticated/rfqs/new': typeof AuthenticatedRfqsNewRoute
  '/_authenticated/room-types/$id': typeof AuthenticatedRoomTypesIdRoute
  '/_authenticated/seasons/$id': typeof AuthenticatedSeasonsIdRoute
  '/_authenticated/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/_authenticated/suppliers/new': typeof AuthenticatedSuppliersNewRoute
  '/_authenticated/taxes/$id': typeof AuthenticatedTaxesIdRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/hotels/': typeof AuthenticatedHotelsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/payables/': typeof AuthenticatedPayablesIndexRoute
  '/_authenticated/quotations/': typeof AuthenticatedQuotationsIndexRoute
  '/_authenticated/rates/': typeof AuthenticatedRatesIndexRoute
  '/_authenticated/receipts/': typeof AuthenticatedReceiptsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/rfqs/': typeof AuthenticatedRfqsIndexRoute
  '/_authenticated/room-types/': typeof AuthenticatedRoomTypesIndexRoute
  '/_authenticated/seasons/': typeof AuthenticatedSeasonsIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/_authenticated/taxes/': typeof AuthenticatedTaxesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/settings'
    | '/users'
    | '/bookings/$id'
    | '/bookings/new'
    | '/contracts/$id'
    | '/contracts/new'
    | '/customers/$id'
    | '/customers/new'
    | '/hotels/$id'
    | '/hotels/new'
    | '/invoices/$id'
    | '/quotations/$id'
    | '/quotations/new'
    | '/rates/$id'
    | '/rates/compare'
    | '/rates/new'
    | '/reports/financial'
    | '/reports/operational'
    | '/reports/tax'
    | '/reports/templates'
    | '/rfqs/$id'
    | '/rfqs/new'
    | '/room-types/$id'
    | '/seasons/$id'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/taxes/$id'
    | '/bookings/'
    | '/contracts/'
    | '/customers/'
    | '/hotels/'
    | '/invoices/'
    | '/payables/'
    | '/quotations/'
    | '/rates/'
    | '/receipts/'
    | '/reports/'
    | '/rfqs/'
    | '/room-types/'
    | '/seasons/'
    | '/suppliers/'
    | '/taxes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/audit'
    | '/settings'
    | '/users'
    | '/'
    | '/bookings/$id'
    | '/bookings/new'
    | '/contracts/$id'
    | '/contracts/new'
    | '/customers/$id'
    | '/customers/new'
    | '/hotels/$id'
    | '/hotels/new'
    | '/invoices/$id'
    | '/quotations/$id'
    | '/quotations/new'
    | '/rates/$id'
    | '/rates/compare'
    | '/rates/new'
    | '/reports/financial'
    | '/reports/operational'
    | '/reports/tax'
    | '/reports/templates'
    | '/rfqs/$id'
    | '/rfqs/new'
    | '/room-types/$id'
    | '/seasons/$id'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/taxes/$id'
    | '/bookings'
    | '/contracts'
    | '/customers'
    | '/hotels'
    | '/invoices'
    | '/payables'
    | '/quotations'
    | '/rates'
    | '/receipts'
    | '/reports'
    | '/rfqs'
    | '/room-types'
    | '/seasons'
    | '/suppliers'
    | '/taxes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/bookings/new'
    | '/_authenticated/contracts/$id'
    | '/_authenticated/contracts/new'
    | '/_authenticated/customers/$id'
    | '/_authenticated/customers/new'
    | '/_authenticated/hotels/$id'
    | '/_authenticated/hotels/new'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/quotations/$id'
    | '/_authenticated/quotations/new'
    | '/_authenticated/rates/$id'
    | '/_authenticated/rates/compare'
    | '/_authenticated/rates/new'
    | '/_authenticated/reports/financial'
    | '/_authenticated/reports/operational'
    | '/_authenticated/reports/tax'
    | '/_authenticated/reports/templates'
    | '/_authenticated/rfqs/$id'
    | '/_authenticated/rfqs/new'
    | '/_authenticated/room-types/$id'
    | '/_authenticated/seasons/$id'
    | '/_authenticated/suppliers/$id'
    | '/_authenticated/suppliers/new'
    | '/_authenticated/taxes/$id'
    | '/_authenticated/bookings/'
    | '/_authenticated/contracts/'
    | '/_authenticated/customers/'
    | '/_authenticated/hotels/'
    | '/_authenticated/invoices/'
    | '/_authenticated/payables/'
    | '/_authenticated/quotations/'
    | '/_authenticated/rates/'
    | '/_authenticated/receipts/'
    | '/_authenticated/reports/'
    | '/_authenticated/rfqs/'
    | '/_authenticated/room-types/'
    | '/_authenticated/seasons/'
    | '/_authenticated/suppliers/'
    | '/_authenticated/taxes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taxes/': {
      id: '/_authenticated/taxes/'
      path: '/taxes'
      fullPath: '/taxes/'
      preLoaderRoute: typeof AuthenticatedTaxesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seasons/': {
      id: '/_authenticated/seasons/'
      path: '/seasons'
      fullPath: '/seasons/'
      preLoaderRoute: typeof AuthenticatedSeasonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/room-types/': {
      id: '/_authenticated/room-types/'
      path: '/room-types'
      fullPath: '/room-types/'
      preLoaderRoute: typeof AuthenticatedRoomTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfqs/': {
      id: '/_authenticated/rfqs/'
      path: '/rfqs'
      fullPath: '/rfqs/'
      preLoaderRoute: typeof AuthenticatedRfqsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts/': {
      id: '/_authenticated/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof AuthenticatedReceiptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rates/': {
      id: '/_authenticated/rates/'
      path: '/rates'
      fullPath: '/rates/'
      preLoaderRoute: typeof AuthenticatedRatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/': {
      id: '/_authenticated/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AuthenticatedQuotationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payables/': {
      id: '/_authenticated/payables/'
      path: '/payables'
      fullPath: '/payables/'
      preLoaderRoute: typeof AuthenticatedPayablesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotels/': {
      id: '/_authenticated/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof AuthenticatedHotelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taxes/$id': {
      id: '/_authenticated/taxes/$id'
      path: '/taxes/$id'
      fullPath: '/taxes/$id'
      preLoaderRoute: typeof AuthenticatedTaxesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/new': {
      id: '/_authenticated/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof AuthenticatedSuppliersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/$id': {
      id: '/_authenticated/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AuthenticatedSuppliersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seasons/$id': {
      id: '/_authenticated/seasons/$id'
      path: '/seasons/$id'
      fullPath: '/seasons/$id'
      preLoaderRoute: typeof AuthenticatedSeasonsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/room-types/$id': {
      id: '/_authenticated/room-types/$id'
      path: '/room-types/$id'
      fullPath: '/room-types/$id'
      preLoaderRoute: typeof AuthenticatedRoomTypesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfqs/new': {
      id: '/_authenticated/rfqs/new'
      path: '/rfqs/new'
      fullPath: '/rfqs/new'
      preLoaderRoute: typeof AuthenticatedRfqsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfqs/$id': {
      id: '/_authenticated/rfqs/$id'
      path: '/rfqs/$id'
      fullPath: '/rfqs/$id'
      preLoaderRoute: typeof AuthenticatedRfqsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/templates': {
      id: '/_authenticated/reports/templates'
      path: '/reports/templates'
      fullPath: '/reports/templates'
      preLoaderRoute: typeof AuthenticatedReportsTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/tax': {
      id: '/_authenticated/reports/tax'
      path: '/reports/tax'
      fullPath: '/reports/tax'
      preLoaderRoute: typeof AuthenticatedReportsTaxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/operational': {
      id: '/_authenticated/reports/operational'
      path: '/reports/operational'
      fullPath: '/reports/operational'
      preLoaderRoute: typeof AuthenticatedReportsOperationalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/financial': {
      id: '/_authenticated/reports/financial'
      path: '/reports/financial'
      fullPath: '/reports/financial'
      preLoaderRoute: typeof AuthenticatedReportsFinancialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rates/new': {
      id: '/_authenticated/rates/new'
      path: '/rates/new'
      fullPath: '/rates/new'
      preLoaderRoute: typeof AuthenticatedRatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rates/compare': {
      id: '/_authenticated/rates/compare'
      path: '/rates/compare'
      fullPath: '/rates/compare'
      preLoaderRoute: typeof AuthenticatedRatesCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rates/$id': {
      id: '/_authenticated/rates/$id'
      path: '/rates/$id'
      fullPath: '/rates/$id'
      preLoaderRoute: typeof AuthenticatedRatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/new': {
      id: '/_authenticated/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof AuthenticatedQuotationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/$id': {
      id: '/_authenticated/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof AuthenticatedQuotationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotels/new': {
      id: '/_authenticated/hotels/new'
      path: '/hotels/new'
      fullPath: '/hotels/new'
      preLoaderRoute: typeof AuthenticatedHotelsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotels/$id': {
      id: '/_authenticated/hotels/$id'
      path: '/hotels/$id'
      fullPath: '/hotels/$id'
      preLoaderRoute: typeof AuthenticatedHotelsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/new': {
      id: '/_authenticated/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthenticatedCustomersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/new': {
      id: '/_authenticated/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof AuthenticatedContractsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/$id': {
      id: '/_authenticated/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof AuthenticatedContractsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/new': {
      id: '/_authenticated/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof AuthenticatedBookingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
  AuthenticatedBookingsNewRoute: typeof AuthenticatedBookingsNewRoute
  AuthenticatedContractsIdRoute: typeof AuthenticatedContractsIdRoute
  AuthenticatedContractsNewRoute: typeof AuthenticatedContractsNewRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedCustomersNewRoute: typeof AuthenticatedCustomersNewRoute
  AuthenticatedHotelsIdRoute: typeof AuthenticatedHotelsIdRoute
  AuthenticatedHotelsNewRoute: typeof AuthenticatedHotelsNewRoute
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedQuotationsIdRoute: typeof AuthenticatedQuotationsIdRoute
  AuthenticatedQuotationsNewRoute: typeof AuthenticatedQuotationsNewRoute
  AuthenticatedRatesIdRoute: typeof AuthenticatedRatesIdRoute
  AuthenticatedRatesCompareRoute: typeof AuthenticatedRatesCompareRoute
  AuthenticatedRatesNewRoute: typeof AuthenticatedRatesNewRoute
  AuthenticatedReportsFinancialRoute: typeof AuthenticatedReportsFinancialRoute
  AuthenticatedReportsOperationalRoute: typeof AuthenticatedReportsOperationalRoute
  AuthenticatedReportsTaxRoute: typeof AuthenticatedReportsTaxRoute
  AuthenticatedReportsTemplatesRoute: typeof AuthenticatedReportsTemplatesRoute
  AuthenticatedRfqsIdRoute: typeof AuthenticatedRfqsIdRoute
  AuthenticatedRfqsNewRoute: typeof AuthenticatedRfqsNewRoute
  AuthenticatedRoomTypesIdRoute: typeof AuthenticatedRoomTypesIdRoute
  AuthenticatedSeasonsIdRoute: typeof AuthenticatedSeasonsIdRoute
  AuthenticatedSuppliersIdRoute: typeof AuthenticatedSuppliersIdRoute
  AuthenticatedSuppliersNewRoute: typeof AuthenticatedSuppliersNewRoute
  AuthenticatedTaxesIdRoute: typeof AuthenticatedTaxesIdRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedHotelsIndexRoute: typeof AuthenticatedHotelsIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedPayablesIndexRoute: typeof AuthenticatedPayablesIndexRoute
  AuthenticatedQuotationsIndexRoute: typeof AuthenticatedQuotationsIndexRoute
  AuthenticatedRatesIndexRoute: typeof AuthenticatedRatesIndexRoute
  AuthenticatedReceiptsIndexRoute: typeof AuthenticatedReceiptsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedRfqsIndexRoute: typeof AuthenticatedRfqsIndexRoute
  AuthenticatedRoomTypesIndexRoute: typeof AuthenticatedRoomTypesIndexRoute
  AuthenticatedSeasonsIndexRoute: typeof AuthenticatedSeasonsIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
  AuthenticatedTaxesIndexRoute: typeof AuthenticatedTaxesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
  AuthenticatedBookingsNewRoute: AuthenticatedBookingsNewRoute,
  AuthenticatedContractsIdRoute: AuthenticatedContractsIdRoute,
  AuthenticatedContractsNewRoute: AuthenticatedContractsNewRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedCustomersNewRoute: AuthenticatedCustomersNewRoute,
  AuthenticatedHotelsIdRoute: AuthenticatedHotelsIdRoute,
  AuthenticatedHotelsNewRoute: AuthenticatedHotelsNewRoute,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedQuotationsIdRoute: AuthenticatedQuotationsIdRoute,
  AuthenticatedQuotationsNewRoute: AuthenticatedQuotationsNewRoute,
  AuthenticatedRatesIdRoute: AuthenticatedRatesIdRoute,
  AuthenticatedRatesCompareRoute: AuthenticatedRatesCompareRoute,
  AuthenticatedRatesNewRoute: AuthenticatedRatesNewRoute,
  AuthenticatedReportsFinancialRoute: AuthenticatedReportsFinancialRoute,
  AuthenticatedReportsOperationalRoute: AuthenticatedReportsOperationalRoute,
  AuthenticatedReportsTaxRoute: AuthenticatedReportsTaxRoute,
  AuthenticatedReportsTemplatesRoute: AuthenticatedReportsTemplatesRoute,
  AuthenticatedRfqsIdRoute: AuthenticatedRfqsIdRoute,
  AuthenticatedRfqsNewRoute: AuthenticatedRfqsNewRoute,
  AuthenticatedRoomTypesIdRoute: AuthenticatedRoomTypesIdRoute,
  AuthenticatedSeasonsIdRoute: AuthenticatedSeasonsIdRoute,
  AuthenticatedSuppliersIdRoute: AuthenticatedSuppliersIdRoute,
  AuthenticatedSuppliersNewRoute: AuthenticatedSuppliersNewRoute,
  AuthenticatedTaxesIdRoute: AuthenticatedTaxesIdRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedHotelsIndexRoute: AuthenticatedHotelsIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedPayablesIndexRoute: AuthenticatedPayablesIndexRoute,
  AuthenticatedQuotationsIndexRoute: AuthenticatedQuotationsIndexRoute,
  AuthenticatedRatesIndexRoute: AuthenticatedRatesIndexRoute,
  AuthenticatedReceiptsIndexRoute: AuthenticatedReceiptsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedRfqsIndexRoute: AuthenticatedRfqsIndexRoute,
  AuthenticatedRoomTypesIndexRoute: AuthenticatedRoomTypesIndexRoute,
  AuthenticatedSeasonsIndexRoute: AuthenticatedSeasonsIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
  AuthenticatedTaxesIndexRoute: AuthenticatedTaxesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
